import re


_re_space = re.compile(r'(?<![()\[\]{}%\'"A-Za-z]) (?![()\[\]{}%\'"A-Za-z])', re.NOFLAG)
symbols = [' ', '(', ')', '[', ']', '-', '{', '}', '%', "'", '"', ',']


class RuneTrieNode:
    def __init__(self):
        self.child = {}
        self.value = None


class RuneTrie:
    def __init__(self):
        self.__root = RuneTrieNode()

    def put_if_absent(self, key: str, value) -> bool:
        if value is None:
            raise ValueError('cannot put a nil value')
        key = key.lower()
        node = self.__root
        for c in key:
            n = node.child.get(c)
            if n:
                node = n
            else:
                new_node = RuneTrieNode()
                node.child[c] = new_node
                node = new_node
        if node.value:
            return False
        node.value = value
        return True

    def __get_longest(self, s: str) -> (str, str):
        node2 = None
        key2 = ''
        node = self.__root
        key = ''
        for idx in range(len(s)):
            c = s[idx]
            n = node.child.get(c.lower())
            if n:
                key += c
                node = n
                if node.value is not None and (idx + 1 >= len(s) or s[idx + 1] in symbols):
                    node2 = node
                    key2 = key
            else:
                break
        if node2:
            return key2, node2.value
        return '', ''

    def replace_all(self, s: str) -> str:
        s2 = ''
        while s:
            if not (len(s2) == 0 or s2[-1] in symbols):
                s2 += s[0]
                s = s[1:]
                continue
            key, value = self.__get_longest(s)
            if key:
                s2 += value
                s = s[len(key):]
            else:
                s2 += s[0]
                s = s[1:]
        return s2 if s2 == s else _re_space.sub('', s2)


trie = RuneTrie()

trie.put_if_absent("Abyss","深渊")
trie.put_if_absent("Shriek","尖啸")
trie.put_if_absent("Skill","技能")
trie.put_if_absent("Crystal Heart","水晶之心")
trie.put_if_absent("Crystal","水晶")
trie.put_if_absent("Crystal Peaks","水晶山峰")
trie.put_if_absent("Peak","山峰")
trie.put_if_absent("Slash","劈砍")
trie.put_if_absent("Cyclone","旋风")
trie.put_if_absent("Descending Dark","黑暗降临")
trie.put_if_absent("Desolate Dive","荒芜俯冲")
trie.put_if_absent("Dream Gate","梦之门")
trie.put_if_absent("Dream Nail","梦之钉")
trie.put_if_absent("Awoken","觉醒的")
trie.put_if_absent("Dash","冲刺")
trie.put_if_absent("Great Slash","强力劈砍")
trie.put_if_absent("Howling Wraiths","嚎叫幽灵")
trie.put_if_absent("Tram Pass","电车票")
trie.put_if_absent("Item","物品")
trie.put_if_absent("Mask","面具")
trie.put_if_absent("Fragment","碎片")
trie.put_if_absent("Nail","骨钉")
trie.put_if_absent("Vessel","容器")
trie.put_if_absent("Isma's Tear","伊思玛的眼泪")
trie.put_if_absent("Mantis","螳螂")
trie.put_if_absent("Mantis Claw","螳螂爪")
trie.put_if_absent("Monarch Wings","帝王之翼")
trie.put_if_absent("Mothwing","蛾翼")
trie.put_if_absent("Cloak","披风")
trie.put_if_absent("Shade","暗影")
trie.put_if_absent("Shade Soul","暗影之魂")
trie.put_if_absent("Sharp Shadow","锋利之影")
trie.put_if_absent("Vengeful Spirit","复仇之魂")
trie.put_if_absent("Pale","苍白")
trie.put_if_absent("Ore","矿石")
trie.put_if_absent("Any","任意")
trie.put_if_absent("Any%","Any%")
trie.put_if_absent("Simple","简单")
trie.put_if_absent("Key - First","钥匙-第一把")
trie.put_if_absent("Key","钥匙")
trie.put_if_absent("City Crest","城市纹章")
trie.put_if_absent("Mr. Mushroom","蘑菇先生")
trie.put_if_absent("Spot","地点")
trie.put_if_absent("City Of Tears","泪水之城")
trie.put_if_absent("Colosseum","斗兽场")
trie.put_if_absent("White Palace - Workshop","白色宫殿-工作室")
trie.put_if_absent("NKG Dream","梦魇之王格林梦境")
trie.put_if_absent("Transition","切换场景")
trie.put_if_absent("Crest","纹章")
trie.put_if_absent("Dream Wielder","舞梦者")
trie.put_if_absent("Delicate Flower","娇嫩的花")
trie.put_if_absent("Salubra's","萨鲁巴的")
trie.put_if_absent("Blessing","祝福")
trie.put_if_absent("Elegant","典雅的")
trie.put_if_absent("Shoptimisation","和面具碎片1")
trie.put_if_absent("God Tuner","神明调谐器")
trie.put_if_absent("Hunter's Mark","猎人的印记")
trie.put_if_absent("Kings Brand","王之印记")
trie.put_if_absent("Love Key","爱之钥")
trie.put_if_absent("Lumafly Lantern","光蝇灯笼")
trie.put_if_absent("Lurker","潜伏者")
trie.put_if_absent("Shopkeeper's","店主的")
trie.put_if_absent("Upgrade","升级")
trie.put_if_absent("Broken Vessel","残破容器")
trie.put_if_absent("Brooding","躁郁的")
trie.put_if_absent("Mawlek","毛里克")
trie.put_if_absent("Collector","收藏家")
trie.put_if_absent("Guardian","守卫")
trie.put_if_absent("Dung","粪虫")
trie.put_if_absent("Defender","防御者")
trie.put_if_absent("Dung Defender Idol","粪虫防御者神像")
trie.put_if_absent("Trinket","装饰品")
trie.put_if_absent("Elder Hu","胡长老")
trie.put_if_absent("Essence","精华")
trie.put_if_absent("Boss","Boss")
trie.put_if_absent("False","假")
trie.put_if_absent("Knight","骑士")
trie.put_if_absent("Hollow","空洞")
trie.put_if_absent("Failed","失败")
trie.put_if_absent("Champion","冠军")
trie.put_if_absent("Flukemarm","吸虫之母")
trie.put_if_absent("Galien","加利安")
trie.put_if_absent("God Tamer","神之驯服者")
trie.put_if_absent("Gorb","戈布")
trie.put_if_absent("Grey","灰色")
trie.put_if_absent("Prince","王子")
trie.put_if_absent("Zote","左特")
trie.put_if_absent("Gruz Mother","格鲁兹之母")
trie.put_if_absent("Hive","蜂巢")
trie.put_if_absent("Hornet","大黄蜂")
trie.put_if_absent("Lost Kin","失落近亲")
trie.put_if_absent("Mantis Lords","螳螂领主")
trie.put_if_absent("Markoth","马科斯")
trie.put_if_absent("Marmu","马尔穆")
trie.put_if_absent("Mega","大型")
trie.put_if_absent("Massive","大型")
trie.put_if_absent("Moss","苔藓")
trie.put_if_absent("Charger","冲锋者")
trie.put_if_absent("Nightmare King","梦魇之王")
trie.put_if_absent("Grimm","格林")
trie.put_if_absent("Nightmare","梦魇")
trie.put_if_absent("No Eyes","无眼")
trie.put_if_absent("Nosk","诺斯克")
trie.put_if_absent("Oblobbles","奥波路波")
trie.put_if_absent("Oro & Mato Nail Bros","骨钉兄弟奥罗&马托")
trie.put_if_absent("Oro","奥罗")
trie.put_if_absent("Mato","马托")
trie.put_if_absent("Bros","兄弟")
trie.put_if_absent("Pure","纯粹")
trie.put_if_absent("Segment Practice","片段练习")
trie.put_if_absent("Radiance","辐光")
trie.put_if_absent("THK","空洞骑士")
trie.put_if_absent("Sheo Paintmaster","绘画大师席奥")
trie.put_if_absent("Sly Nailsage","骨钉贤者斯莱")
trie.put_if_absent("Soul","灵魂")
trie.put_if_absent("Master","大师")
trie.put_if_absent("Tyrant","暴君")
trie.put_if_absent("Troupe Master","剧团团长")
trie.put_if_absent("Traitor Lord","叛徒领主")
trie.put_if_absent("Uumuu","乌姆")
trie.put_if_absent("Watcher","守望者")
trie.put_if_absent("White","白色")
trie.put_if_absent("Xero","泽若")
trie.put_if_absent("Vengefly King","反击蝇之王")
trie.put_if_absent("Enraged","暴怒")
trie.put_if_absent("Grub","幼虫")
trie.put_if_absent("Dreamer","守梦者")
trie.put_if_absent("Herrah the Beast","野兽赫拉")
trie.put_if_absent("Lurien the Watcher","守望者卢瑞恩")
trie.put_if_absent("Monomon the Teacher","教师莫诺蒙")
trie.put_if_absent("First Dreamer","第一位守梦者")
trie.put_if_absent("Second Dreamer","第二位守梦者")
trie.put_if_absent("Third Dreamer","第三位守梦者")
trie.put_if_absent("Pre-Grimm Shop","格林前购物")
trie.put_if_absent("Event","事件")
trie.put_if_absent("Sly","斯莱")
trie.put_if_absent("Final Shop","最终购物")
trie.put_if_absent("Can Overcharm","解锁过载")
trie.put_if_absent("Chains Broken","锁链劈断")
trie.put_if_absent("Chandelier","吊灯")
trie.put_if_absent("Knights","骑士")
trie.put_if_absent("City Gate","泪水之城大门")
trie.put_if_absent("Death","死亡")
trie.put_if_absent("Ending","结局")
trie.put_if_absent("Flower Quest","送花任务")
trie.put_if_absent("Reward","奖励")
trie.put_if_absent("Happy Couple","幸福的夫妇")
trie.put_if_absent("Nailsmith","骨钉匠")
trie.put_if_absent("Lantern Lit","火炬点亮")
trie.put_if_absent("Lantern Destroyed","火炬破坏")
trie.put_if_absent("Dream Entry","进入梦境")
trie.put_if_absent("Seer","先知")
trie.put_if_absent("Seer Departs","先知升天")
trie.put_if_absent("Spirit Glade Door","灵魂沼地大门")
trie.put_if_absent("Bench","椅子")
trie.put_if_absent("Trap","陷阱")
trie.put_if_absent("Beasts","野兽")
trie.put_if_absent("Den","巢穴")
trie.put_if_absent("Unlocked","解锁")
trie.put_if_absent("Colosseum Fight","斗兽场战斗")
trie.put_if_absent("Trial","试炼")
trie.put_if_absent("Path of Pain","苦痛之路")
trie.put_if_absent("Completed","完成")
trie.put_if_absent("Aspid Hunter","阿司匹德猎手")
trie.put_if_absent("Aluba","阿鲁巴")
trie.put_if_absent("Killed","击杀")
trie.put_if_absent("Killed/Spared","击杀/赦免")
trie.put_if_absent("Mini Boss","遭遇战")
trie.put_if_absent("Husk Miner","米拉")
trie.put_if_absent("Great Hopper","大跳虫")
trie.put_if_absent("Gorgeous Husk","华丽躯壳")
trie.put_if_absent("Menderbug","维修虫")
trie.put_if_absent("Warrior","战士")
trie.put_if_absent("Sanctum","圣所")
trie.put_if_absent("Twister","扭曲者")
trie.put_if_absent("Shrumal Ogre","拜年菇")
trie.put_if_absent("Rescued","营救")
trie.put_if_absent("Deepnest","深邃巢穴")
trie.put_if_absent("Exit","离开")
trie.put_if_absent("Forgotten","遗忘的")
trie.put_if_absent("Crossroads","十字路")
trie.put_if_absent("Stag Station","鹿角站")
trie.put_if_absent("Map","地图")
trie.put_if_absent("Queen's Station","王后驿站")
trie.put_if_absent("Queen's Garden","王后花园")
trie.put_if_absent("Queen's Gardens","王后花园")
trie.put_if_absent("City Storerooms","城市仓库")
trie.put_if_absent("Kings Station","国王驿站")
trie.put_if_absent("Resting Grounds","安息之地")
trie.put_if_absent("Distant Village","遥远的村庄")
trie.put_if_absent("Hidden Station","隐藏的鹿角站")
trie.put_if_absent("Stagnest","鹿角虫巢穴")
trie.put_if_absent("Ancient Basin","古老盆地")
trie.put_if_absent("Dirtmouth","德特茅斯")
trie.put_if_absent("Fog Canyon","雾之峡谷")
trie.put_if_absent("Fungal Wastes","真菌荒地")
trie.put_if_absent("Godhome","神居")
trie.put_if_absent("Infected","感染的")
trie.put_if_absent("Deepnest Spa","深邃巢穴温泉")
trie.put_if_absent("Kingdom's Edge","王国边境")
trie.put_if_absent("Royal Waterways","皇家水道")
trie.put_if_absent("Teachers Archive","教师档案馆")
trie.put_if_absent("White Palace","白色宫殿")
trie.put_if_absent("Overcharmed","过载")
trie.put_if_absent("w/","和")
trie.put_if_absent("QGA/Mound Entry","酸冲")
trie.put_if_absent("Frogs","雾之峡谷")
trie.put_if_absent("Post-Upper Arena","左上遭遇战")
trie.put_if_absent("has been obtained","被获得")
trie.put_if_absent("King's Pass","国王山道")
trie.put_if_absent("King's Pass From Town","从德特茅斯进入国王山道")
trie.put_if_absent("Enter Any Dream","进入任意梦境")
trie.put_if_absent("Blue Lake","蓝湖")
trie.put_if_absent("Overcharm","过载")
trie.put_if_absent("Has Claw","获得螳螂爪后")
trie.put_if_absent("Waterways Manhole","皇家水道井口")
trie.put_if_absent("Entry","入口")
trie.put_if_absent("Baldur Shell","巴德尔之壳")
trie.put_if_absent("Dashmaster","冲刺大师")
trie.put_if_absent("Deep Focus","深度聚集")
trie.put_if_absent("Dreamshield","梦之盾")
trie.put_if_absent("Defenders","防御者")
trie.put_if_absent("Flukenest","吸虫之巢")
trie.put_if_absent("Fragile","易碎")
trie.put_if_absent("Greed","贪婪")
trie.put_if_absent("Fragile Heart","易碎心脏")
trie.put_if_absent("Strength","力量")
trie.put_if_absent("Fury of the Fallen","亡者之怒")
trie.put_if_absent("Gathering Swarm","蜂群集结")
trie.put_if_absent("Glowing Womb","发光子宫")
trie.put_if_absent("Grimmchild","格林之子")
trie.put_if_absent("Grimmchild Lvl","格林之子等级")
trie.put_if_absent("Carefree Melody","无忧旋律")
trie.put_if_absent("Grubberfly's Elegy","蜕变挽歌")
trie.put_if_absent("Grubsong","幼虫之歌")
trie.put_if_absent("Heavy Blow","沉重之击")
trie.put_if_absent("Hiveblood","蜂巢之血")
trie.put_if_absent("Joni's","乔尼的")
trie.put_if_absent("Kingsoul","国王之魂")
trie.put_if_absent("Queen's","王后")
trie.put_if_absent("King's","国王")
trie.put_if_absent("Lifeblood Core","生命血核心")
trie.put_if_absent("Lifeblood Heart","生命血之心")
trie.put_if_absent("Longnail","修长之钉")
trie.put_if_absent("Mark Of Pride","骄傲印记")
trie.put_if_absent("Nailmaster's Glory","骨钉大师的荣耀")
trie.put_if_absent("Quick","快速")
trie.put_if_absent("Focus","聚集")
trie.put_if_absent("Shaman Stone","萨满之石")
trie.put_if_absent("Shape of Unn","乌恩之形")
trie.put_if_absent("Soul Catcher","灵魂捕手")
trie.put_if_absent("Soul Eater","噬魂者")
trie.put_if_absent("Spell","法术")
trie.put_if_absent("Spore Shroom","蘑菇孢子")
trie.put_if_absent("Sprintmaster","飞毛腿")
trie.put_if_absent("Stalwart Shell","坚硬外壳")
trie.put_if_absent("Steady Body","稳定之体")
trie.put_if_absent("Thorns Of Agony","苦痛荆棘")
trie.put_if_absent("Unbreakable","坚固")
trie.put_if_absent("Unbreakable Heart","坚固心脏")
trie.put_if_absent("Void Heart","虚空之心")
trie.put_if_absent("Wayward Compass","任性的指南针")
trie.put_if_absent("Weaversong","编织者之歌")
trie.put_if_absent("Charm Notch","护符槽")
trie.put_if_absent("Charm","护符")
trie.put_if_absent("Salubra","萨鲁巴")
trie.put_if_absent("Lemm Shop","里姆商店对话")
trie.put_if_absent("Lemm - ACN","里姆全护符槽速通")
trie.put_if_absent("Shrumal Ogres","拜年菇")
trie.put_if_absent("Mourner","哀悼者")
trie.put_if_absent("Met","见到")
trie.put_if_absent("Ascended","升天")
trie.put_if_absent("Elderbug Flower Quest","虫长者送花")
trie.put_if_absent("Godseeker Flower","寻神者送花")
trie.put_if_absent("Oro Flower","奥罗送花")
trie.put_if_absent("White Lady Flower","白色夫人送花")
trie.put_if_absent("Emilitia Flower","艾米丽塔送花")
trie.put_if_absent("Bretta","布蕾塔")
trie.put_if_absent("Brumm","布鲁姆")
trie.put_if_absent("Flame","火焰")
trie.put_if_absent("Little Fool","小愚人")
trie.put_if_absent("NPC","NPC")
trie.put_if_absent("Basin Dive","盆地下砸")
trie.put_if_absent("Basin Wings","盆地二段跳")
trie.put_if_absent("City Below Love Tower","爱之塔下")
trie.put_if_absent("City Below Sanctum","圣所下")
trie.put_if_absent("City Guard House","泪城守卫房间")
trie.put_if_absent("City Sanctum","圣所")
trie.put_if_absent("City Spire","守望者的尖塔")
trie.put_if_absent("City Collector","收藏家")
trie.put_if_absent("City Collector All","收藏家全部")
trie.put_if_absent("Cliffs Baldur Shell","巴德尔之壳")
trie.put_if_absent("Crossroads Acid","十字路酸水")
trie.put_if_absent("Crossroads Guarded","十字路龙牙哥")
trie.put_if_absent("Crossroads Wall","十字路隐藏墙")
trie.put_if_absent("Spikes","尖刺")
trie.put_if_absent("Vengefly","反击蝇")
trie.put_if_absent("Crushers","粉碎机")
trie.put_if_absent("Crystal Peaks Crown","圣巢之巅")
trie.put_if_absent("Crystal Peaks Mound","结晶山丘")
trie.put_if_absent("Bottom Lever","下层")
trie.put_if_absent("Beast's","野兽")
trie.put_if_absent("Deepnest Dark","深邃巢穴摸黑房间")
trie.put_if_absent("Mimics","假幼虫")
trie.put_if_absent("Mimic","假幼虫")
trie.put_if_absent("Archives","档案馆")
trie.put_if_absent("Fungal Bouncy","真菌荒地弹跳")
trie.put_if_absent("Fungal Spore Shroom","真菌荒地蘑菇孢子")
trie.put_if_absent("Cornifer","柯尼法")
trie.put_if_absent("Hunter","猎人")
trie.put_if_absent("Hive External","蜂巢外")
trie.put_if_absent("Hive Internal","蜂巢内")
trie.put_if_absent("Kingdom's Edge Center","王国边境中间")
trie.put_if_absent("Below Stag","鹿角站下")
trie.put_if_absent("Queen's Gardens Upper","王后花园顶")
trie.put_if_absent("White Lady","白色夫人")
trie.put_if_absent("Crypts","地窖")
trie.put_if_absent("Waterways Center","皇家水道中间")
trie.put_if_absent("Waterways Hwurmps","皇家水道王国边境")
trie.put_if_absent("Waterways Isma","伊思玛")
trie.put_if_absent("Area","区域")
trie.put_if_absent("Ancestral Mound","祖先山丘")
trie.put_if_absent("Crystal Peak","水晶山峰")
trie.put_if_absent("Forgotten Crossroads","十字路")
trie.put_if_absent("Leg Eater","食腿者")
trie.put_if_absent("Mantis Village","螳螂村")
trie.put_if_absent("Greenpath","苍绿之径")
trie.put_if_absent("Howling Cliffs","呼啸悬崖")
trie.put_if_absent("Spirits' Glade","灵魂沼地")
trie.put_if_absent("Toll","收费机")
trie.put_if_absent("Basin Bench","古老盆地椅子")
trie.put_if_absent("Tram Deepnest","深邃巢穴电车")
trie.put_if_absent("Tram","电车")
trie.put_if_absent("Left Orb","中层左灯")
trie.put_if_absent("Right Orb","中层右灯")
trie.put_if_absent("Lower Entry","下层入口")
trie.put_if_absent("Lower Orb","下层灯")
trie.put_if_absent("Room","房间")
trie.put_if_absent("Left Entry","中层左入口")
trie.put_if_absent("Left Midpoint","中层左中间")
trie.put_if_absent("Right Side Entry","中层右入口")
trie.put_if_absent("Right Side Climb","中层右攀爬房间")
trie.put_if_absent("Right Side Saw Squeeze","中层右锯挤房间")
trie.put_if_absent("Right Side Exit","中层右出口")
trie.put_if_absent("Top Entry","上层入口")
trie.put_if_absent("Top Cursed Cycle","上层诅咒循环")
trie.put_if_absent("Top Lever","上层上")
trie.put_if_absent("Top Final Platforming","上层最后平台")
trie.put_if_absent("Throne Room","上层王座")
trie.put_if_absent("Atrium","中庭")
trie.put_if_absent("Path of Pain Room","苦痛之路进入房间")
trie.put_if_absent("Kingdom's Edge Acid","王国边境酸水旁放梦之门")
trie.put_if_absent("Dreamgate","梦之门")
trie.put_if_absent("Encountered","遭遇")
trie.put_if_absent("Practice","试炼")
trie.put_if_absent("Godhome Bench","万神殿椅子")
trie.put_if_absent("Godhome Lore Room","万神殿寻神者房间")
trie.put_if_absent("Pantheon","万神殿")
trie.put_if_absent("Main Menu","回主菜单")
trie.put_if_absent("Main Menu w/ Claw","回主菜单获得螳螂爪后")
trie.put_if_absent("Main Menu w/ Ghusk","回主菜单击杀华丽躯壳后")
trie.put_if_absent("Menu","菜单")
trie.put_if_absent("Cornifer at Home","柯尼法在家")
trie.put_if_absent("All Seals","全部圣巢印章")
trie.put_if_absent("All Eggs","全部腐臭蛋")
trie.put_if_absent("Sly Simple Key","斯莱商店的简单钥匙")
trie.put_if_absent("All Breakables","易碎护符全损坏")
trie.put_if_absent("All Unbreakables","坚固护符全获得")
trie.put_if_absent("Emilitia","艾米丽塔")
trie.put_if_absent("Waterways","皇家水道")
trie.put_if_absent("Dream Nail Marissa","梦之钉吸收玛丽莎")
trie.put_if_absent("Obtain","获得")
trie.put_if_absent("Dream Nail Caelif and Fera","梦之钉吸收凯利福与菲拉")
trie.put_if_absent("Dream Nail Poggy","梦之钉吸收波奇")
trie.put_if_absent("Dream Nail Gravedigger","梦之钉吸收掘墓者")
trie.put_if_absent("Dream Nail Joni","梦之钉吸收乔尼")
trie.put_if_absent("Dream Nail Cloth","梦之钉吸收阿布")
trie.put_if_absent("Dream Nail Vespa","梦之钉吸收维斯帕")
trie.put_if_absent("Dream Nail Revek","梦之钉吸收瑞维克")
trie.put_if_absent("Wanderer's Journal","漫游者日记")
trie.put_if_absent("Hallownest Seal","圣巢印章")
trie.put_if_absent("King's Idol","国王神像")
trie.put_if_absent("Arcane Egg","神秘蛋")
trie.put_if_absent("Rancid Egg","腐臭蛋")
trie.put_if_absent("Mask Shard","面具碎片")
trie.put_if_absent("Use Simple Key","使用简单钥匙")
trie.put_if_absent("Any Transition","切换任意场景")
trie.put_if_absent("Manual Split","手动分段")
trie.put_if_absent("Misc","其它")
trie.put_if_absent("Round","奥波路波")
trie.put_if_absent("All Breakable Charms","全易碎护符")
trie.put_if_absent("Ghostbusters","鬼魂破坏者")
trie.put_if_absent("Godhome Ending","神居结局")
trie.put_if_absent("All Unbreakable Charms","全坚固护符")
trie.put_if_absent("Steel Soul","钢魂")
trie.put_if_absent("A1uba","阿鲁巴一只")
trie.put_if_absent("Vessel Fragments","容器碎片")
trie.put_if_absent("9 Vessel Fragments","9容器碎片")
trie.put_if_absent("Worldsoul","世界之魂")
trie.put_if_absent("Cartographer","柯尼法在家")
trie.put_if_absent("P1","1门")
trie.put_if_absent("P2","2门")
trie.put_if_absent("P3","3门")
trie.put_if_absent("P4","4门")
trie.put_if_absent("P5","5门")
trie.put_if_absent("Pantheon of the Master","大师万神殿")
trie.put_if_absent("Pantheon of the Artist","艺术家万神殿")
trie.put_if_absent("Pantheon of the Sage","贤者万神殿")
trie.put_if_absent("Pantheon of the Knight","骑士万神殿")
trie.put_if_absent("Pantheon of Hallownest","圣巢万神殿")
trie.put_if_absent("Fool","愚人的试炼")
trie.put_if_absent("True","真")
trie.put_if_absent("Mask Shards","面具碎片")
trie.put_if_absent("Geo","吉欧")
trie.put_if_absent("ACN","全护符槽")
trie.put_if_absent("No Shop Charms","不在商店买护符")
trie.put_if_absent("Egg 21","腐臭蛋21个")
trie.put_if_absent("All Skills","全技能")
trie.put_if_absent("All Glitches","允许所有邪道")
trie.put_if_absent("colo1","斗兽场1")
trie.put_if_absent("colo2","斗兽场2")
trie.put_if_absent("colo3","斗兽场3")
trie.put_if_absent("Florist","花匠")
trie.put_if_absent("GPZ","灰色王子左特")
trie.put_if_absent("Current Patch","当前版本")
trie.put_if_absent("Eat Me Too","把我也吃了吧")
trie.put_if_absent("Witness","见证")
trie.put_if_absent("Current Patch NMG","当前版本无主要邪道")
trie.put_if_absent("No Major Glitches","无主要邪道")
trie.put_if_absent("TE","真结局")
trie.put_if_absent("Flukamoth","吸虫")
trie.put_if_absent("AB","全BOSS")
trie.put_if_absent("APB","全万神殿BOSS")
trie.put_if_absent("Any (1.4.3.2) w/ Spore Shroom","Any(1.4.3.2)蘑菇孢子路线")
trie.put_if_absent("1.4+ Shriek","1.4+版本吼路线")
trie.put_if_absent("Al2ba","阿鲁巴两只")
trie.put_if_absent("All Charm Notches","全护符槽")
trie.put_if_absent("All Keys","全钥匙")
trie.put_if_absent("All Stag Stations","全鹿角站")
trie.put_if_absent("All Wanderer's Journals","全漫游者日记")
trie.put_if_absent("All Geo Chests","全吉欧堆")
trie.put_if_absent("All Whispering Roots","全低语之根")
trie.put_if_absent("Clawless","无螳螂爪")
trie.put_if_absent("Elderbug","虫长者送花")
trie.put_if_absent("Spelless","无法术")
trie.put_if_absent("Marissa Audience","玛丽莎的听众")
trie.put_if_absent("Myla","米拉")
trie.put_if_absent("Myla's Revenge","米拉的复仇")
trie.put_if_absent("NKG","梦魇之王格林")
trie.put_if_absent("NMG","骨钉大师的荣耀")
trie.put_if_absent("Save Myla","拯救米拉")
trie.put_if_absent("Save Myla Dash Slash route","拯救米拉-冲刺劈砍路线")
trie.put_if_absent("Pantheon 5 Boss Order","在流程中按5门顺序击杀BOSS")
trie.put_if_absent("Enraged Guardian","暴怒守卫")
trie.put_if_absent("Absolute Radiance","无上辐光")
trie.put_if_absent("Eternal Ordeal Unlocked","无尽折磨解锁")
trie.put_if_absent("Eternal Ordeal Achieved","无尽折磨完成")
trie.put_if_absent("Transition excluding Save State Transition","任意切换场景但不含SaveState切换场景")
trie.put_if_absent("Sanctum w/ Shade Soul","暗影之魂后进入圣所")
trie.put_if_absent("Mourner w/ Seer Ascended","先知升天后对话灰色哀悼者")
trie.put_if_absent("Greenpath w/ Unlocked Overcharm","过载进入苍绿之径")
trie.put_if_absent("Mask Fragment","面具碎片")
trie.put_if_absent("Vessel Fragment","容器碎片")
trie.put_if_absent("Pale Ore","苍白矿石")
trie.put_if_absent("Grimm Flame","格林火焰")
trie.put_if_absent("Enter","进入")
trie.put_if_absent("Embrace the Void","拥抱虚空")
trie.put_if_absent("Spire","守望者的尖塔")
trie.put_if_absent("Watcher Spire","守望者的尖塔")
trie.put_if_absent("Basin","盆地")
trie.put_if_absent("The Radiance","辐光")
trie.put_if_absent("Black Egg Temple","黑卵圣殿")
trie.put_if_absent("Lake of Unn","乌恩之湖")
trie.put_if_absent("Teacher's Archive","教师档案馆")
trie.put_if_absent("Elegy","蜕变挽歌")
trie.put_if_absent("Egg 101","腐臭蛋101个")
trie.put_if_absent("All Hallownest Seals","全圣巢印章")
trie.put_if_absent("All King's Idols","全国王神像")
trie.put_if_absent("Storerooms","城市仓库")
trie.put_if_absent("VF","容器碎片")
trie.put_if_absent("King's Station","国王驿站")
trie.put_if_absent("Basin Fountain","盆地喷泉")
trie.put_if_absent("Weaver's Chest","编织者吉欧堆")
trie.put_if_absent("Idol in Crystal Peaks","水晶山峰神像")
trie.put_if_absent("Idol after Dung Defender","粪虫防御者神像")
trie.put_if_absent("Idol in Howling Cliffs","呼啸悬崖神像")
trie.put_if_absent("Idol below Zote Arena","左特下方神像")
trie.put_if_absent("Idol at Great Hopper","大跳虫神像")
trie.put_if_absent("Idol at Pale Lurker","苍白潜伏者神像")
trie.put_if_absent("Idol in Spirit's Glade","灵魂沼地神像")
trie.put_if_absent("Idol from Grubfather","虫爷爷神像")
trie.put_if_absent("Rafters Seal","平台印章")
trie.put_if_absent("Sanctum Seal","圣所印章")
trie.put_if_absent("Crypts Seal","地窖印章")
trie.put_if_absent("Seer Seal","先知印章")
trie.put_if_absent("Watcher Knights Seal","守望者骑士印章")
trie.put_if_absent("King's Station Seal","国王驿站印章")
trie.put_if_absent("Well Seal","井印章")
trie.put_if_absent("Upper Fog Canyon Seal","雾之峡谷入口印章")
trie.put_if_absent("Lifeblood Seal","生命血印章")
trie.put_if_absent("Acid Bridge Seal","酸水桥印章")
trie.put_if_absent("Willoh Seal","维洛印章")
trie.put_if_absent("Sporg Seal","核弹菇印章")
trie.put_if_absent("Mantis Lords Seal","螳螂领主印章")
trie.put_if_absent("Deepnest Seal","深邃巢穴印章")
trie.put_if_absent("Frogs Seal","王后花园青蛙房间印章")
trie.put_if_absent("Grubfather Seal","虫爷爷印章")
trie.put_if_absent("Salubra Charms","萨鲁巴护符槽")
trie.put_if_absent("Journal outside Greenpath Stag","苍绿鹿角站外日记")
trie.put_if_absent("Journal above Mantis Village","螳螂村上方日记")
trie.put_if_absent("Journal below Shrumal Ogres","拜年菇下方日记")
trie.put_if_absent("Journal below Stone Sanctuary","石之庇护所下方日记")
trie.put_if_absent("Journal above King's Station","国王驿站上方日记")
trie.put_if_absent("Journal at City Storerooms","城市仓库日记")
trie.put_if_absent("Journal in Crystal Peaks","水晶山峰日记")
trie.put_if_absent("Journal in Howling Cliffs","呼啸悬崖日记")
trie.put_if_absent("Journal below Soul Eater","噬魂者下方日记")
trie.put_if_absent("Journal in Pleasure House","欢乐之屋日记")
trie.put_if_absent("Journal below Broken Bridge","断桥下方日记")
trie.put_if_absent("Journal at Kingdom's Edge Entrance","王国边境入口日记")
trie.put_if_absent("Journal at Camp Bench","帐篷日记")
trie.put_if_absent("Journal near Markoth","马科斯日记")
trie.put_if_absent("Protector","守护者")
trie.put_if_absent("Sentinel","岗哨")
trie.put_if_absent("Crown","圣巢之巅")
trie.put_if_absent("Grubfather","虫爷爷")
trie.put_if_absent("Spike Grub","尖刺幼虫")
trie.put_if_absent("Wall Grub","隐藏墙幼虫")
trie.put_if_absent("Guarded Grub","龙牙哥幼虫")
trie.put_if_absent("Moss Knight Grub","苔藓骑士幼虫")
trie.put_if_absent("Cornifer Grub","柯尼法幼虫")
trie.put_if_absent("Acid Grub","酸水幼虫")
trie.put_if_absent("Bouncy Grub","弹跳幼虫")
trie.put_if_absent("Audience","听众")
trie.put_if_absent("Riding Stag","乘坐鹿角虫")
trie.put_if_absent("Saved Cloth","拯救阿布")
trie.put_if_absent("Crystal Mound Exit","离开结晶山丘")
trie.put_if_absent("Banishment","放逐")
trie.put_if_absent("when","当")
trie.put_if_absent("Splits","分割")
trie.put_if_absent("getting","获得")
trie.put_if_absent("obtaining","获得")
trie.put_if_absent("Nail Art","骨钉技艺")
trie.put_if_absent("absorbing","吸收")
trie.put_if_absent("killing","击杀")
trie.put_if_absent("from","从")
trie.put_if_absent("Trial of the Fool","愚人的试炼")
trie.put_if_absent("Trial of the Conqueror","征服者的试炼")
trie.put_if_absent("Trial of the Warrior","勇士的试炼")
trie.put_if_absent("Aspid Arena","阿司匹德遭遇战")
trie.put_if_absent("Queen Fragment","王后白色碎片")
trie.put_if_absent("King Fragment","国王白色碎片")
trie.put_if_absent("THK Scream","空洞骑士战吼")
trie.put_if_absent("Stag","鹿角虫")
trie.put_if_absent("Enemy","敌人")
trie.put_if_absent("Whispering Root","低语之根")
trie.put_if_absent("Notch","护符槽")
trie.put_if_absent("Root","低语之根")
trie.put_if_absent("Lever","操纵杆")
trie.put_if_absent("Begin Colosseum Trials","开始斗兽场试炼")
trie.put_if_absent("All Bindings","四锁")
trie.put_if_absent("No Main Menu Storage","NMMS")
trie.put_if_absent("Quill","羽毛笔")
trie.put_if_absent("Cocoon","蓝血")
trie.put_if_absent("Hot Spring","温泉")
trie.put_if_absent("Sisters of Battle","战斗姐妹")
trie.put_if_absent("Winged","有翼")
trie.put_if_absent("Shadow Scream","黑吼")
trie.put_if_absent("Super Dash","超冲")
trie.put_if_absent("Shadow Dive","黑砸")
trie.put_if_absent("in","在")
trie.put_if_absent("after","当")
trie.put_if_absent("defeating","击败")
trie.put_if_absent("the","")
trie.put_if_absent("Wall Jump","爬墙")
trie.put_if_absent("Lemm","里姆")
trie.put_if_absent("talking to","对话")
trie.put_if_absent("shop","商店")
trie.put_if_absent("for the first time","第一次")
trie.put_if_absent("the first","第一个")
trie.put_if_absent("the second","第二个")
trie.put_if_absent("the third","第三个")
trie.put_if_absent("Dream","梦境")
trie.put_if_absent("Shadow","暗影")
trie.put_if_absent("beating","击败")
trie.put_if_absent("entering","进入")
trie.put_if_absent("text first appears","文字首次出现")
trie.put_if_absent("Dream No More","不再有梦")
trie.put_if_absent("world","世界")
trie.put_if_absent("a","一个")
trie.put_if_absent("an","一个")
trie.put_if_absent("using","使用")
trie.put_if_absent("excludes","不含")
trie.put_if_absent("Sly's","斯莱的")
trie.put_if_absent("only one will split per transition","每次切换场景只会分割一次")
trie.put_if_absent("Use","使用")
trie.put_if_absent("this","这个")
trie.put_if_absent("you","你")
trie.put_if_absent("need to","需要")
trie.put_if_absent("manually","手动地")
trie.put_if_absent("split","分割")
trie.put_if_absent("subsplit","子分割")
trie.put_if_absent("ordered","排序的")
trie.put_if_absent("and","和")
trie.put_if_absent("enters","进入")
trie.put_if_absent("Joni","乔尼")
trie.put_if_absent("Cloth","阿布")
trie.put_if_absent("Vespa","维斯帕")
trie.put_if_absent("Acid Armour","酸泪")
trie.put_if_absent("you've obtained","你已获得")
trie.put_if_absent("if","如果")
trie.put_if_absent("dropping the chandelier on one of the watcher knights","用吊灯砸死一个守望者骑士")
trie.put_if_absent("Spider","蜘蛛")
trie.put_if_absent("see","看见")
trie.put_if_absent("the mask for Herrah","赫拉的面具")
trie.put_if_absent("the mask for Lurien","卢瑞恩的面具")
trie.put_if_absent("the mask for Monomon","莫诺蒙的面具")
trie.put_if_absent("Rancid Eggs","腐臭蛋")
trie.put_if_absent("acquiring","获得")
trie.put_if_absent("have been collected","已收集")
trie.put_if_absent("Scream","吼")
trie.put_if_absent("extra","额外的")
trie.put_if_absent("1st","第1个")
trie.put_if_absent("2nd","第2个")
trie.put_if_absent("3rd","第3个")
trie.put_if_absent("4th","第4个")
trie.put_if_absent("5th","第5个")
trie.put_if_absent("6th","第6个")
trie.put_if_absent("7th","第7个")
trie.put_if_absent("8th","第8个")
trie.put_if_absent("9th","第9个")
trie.put_if_absent("10th","第10个")
trie.put_if_absent("11th","第11个")
trie.put_if_absent("12th","第12个")
trie.put_if_absent("13th","第13个")
trie.put_if_absent("14th","第14个")
trie.put_if_absent("15th","第15个")
trie.put_if_absent("16th","第16个")
trie.put_if_absent("fourth","第四个")
trie.put_if_absent("fifth","第五个")
trie.put_if_absent("each time","每次")
trie.put_if_absent("Dung Defender's","粪虫防御者的")
trie.put_if_absent("the first time","第一次")
trie.put_if_absent("is activated the first time and the gate closes","首次被激活并且大门关闭")
trie.put_if_absent("placing Dreamgate","放置梦之门")
trie.put_if_absent("by KE Acid","在王国边境酸水旁")
trie.put_if_absent("leaving","离开")
trie.put_if_absent("on entry to","当进入")
trie.put_if_absent("any of","任意一个")
trie.put_if_absent("Hallownest Seals","圣巢印章")
trie.put_if_absent("buying","购买")
trie.put_if_absent("charms","护符")
trie.put_if_absent("charms are broken","护符破碎")
trie.put_if_absent("all","全部")
trie.put_if_absent("are obtained","被获得")
trie.put_if_absent("City","城市")
trie.put_if_absent("QG","王后花园")
trie.put_if_absent("KE","王国边境")
trie.put_if_absent("Marissa","玛丽莎")
trie.put_if_absent("Caelif","凯利福")
trie.put_if_absent("Gravedigger","掘墓者")
trie.put_if_absent("while","当")
trie.put_if_absent("King's Brand","王之印记")
trie.put_if_absent("Glade Idol","灵魂沼地神像")
trie.put_if_absent("Old Dreamer Timing","旧守梦者计时")
trie.put_if_absent("Herrah","赫拉")
trie.put_if_absent("Lurien","卢瑞恩")
trie.put_if_absent("Monomon","莫诺蒙")
trie.put_if_absent("Abyss Door","深渊大门")
trie.put_if_absent("Abyss Lighthouse","深渊灯塔点亮")
trie.put_if_absent("City Gate w/ Mantis Lords defeated","击败螳螂领主后进入泪城大门")
trie.put_if_absent("Credits Roll","滚动开发者名单")
trie.put_if_absent("Lift Opened","电梯解锁")
trie.put_if_absent("Entrance","进入")
trie.put_if_absent("Has Fireball","获得复仇之魂后")
trie.put_if_absent("Has Descending Dark","获得黑暗降临后")
trie.put_if_absent("excluding Save State","但不包括SaveState切换场景")
trie.put_if_absent("Great NailSage","伟大的骨钉贤者")
trie.put_if_absent("Paintmaster","绘画大师")
trie.put_if_absent("Sheo","席奥")
trie.put_if_absent("Defeated","击败")
trie.put_if_absent("Catacombs","地窖")
trie.put_if_absent("Has Isma's Tear","获得伊思玛的眼泪后")
trie.put_if_absent("Isma's Tear with Grub","伊思玛的眼泪和幼虫")
trie.put_if_absent("Tower of Love","爱之塔")
trie.put_if_absent("Crystal Peak Mound","水晶山峰结晶山丘")
trie.put_if_absent("Colo 1 Wave 1a","斗兽场1第1a波")
trie.put_if_absent("Colo 1 Wave 1b","斗兽场1第1b波")
trie.put_if_absent("Colo 1 Wave 1c","斗兽场1第1c波")
trie.put_if_absent("Colo 1 Wave 2","斗兽场1第2波")
trie.put_if_absent("Colo 1 Wave 3a","斗兽场1第3a波")
trie.put_if_absent("Colo 1 Wave 3b","斗兽场1第3b波")
trie.put_if_absent("Colo 1 Wave 4","斗兽场1第4波")
trie.put_if_absent("Colo 1 Wave 5","斗兽场1第5波")
trie.put_if_absent("Colo 1 Wave 6","斗兽场1第6波")
trie.put_if_absent("Colo 1 Wave 7","斗兽场1第7波")
trie.put_if_absent("Colo 1 Wave 8a","斗兽场1第8a波")
trie.put_if_absent("Colo 1 Wave 8b","斗兽场1第8b波")
trie.put_if_absent("Colo 1 Wave 9","斗兽场1第9波")
trie.put_if_absent("Colo 1 Wave 10","斗兽场1第10波")
trie.put_if_absent("Colo 1 Wave 11a","斗兽场1第11a波")
trie.put_if_absent("Colo 1 Wave 11b","斗兽场1第11b波")
trie.put_if_absent("Colo 1 End","斗兽场1结束")
trie.put_if_absent("Colo 2 Wave 1","斗兽场2第1波")
trie.put_if_absent("Colo 2 Wave 2","斗兽场2第2波")
trie.put_if_absent("Colo 2 Wave 3","斗兽场2第3波")
trie.put_if_absent("Colo 2 Wave 4","斗兽场2第4波")
trie.put_if_absent("Colo 2 Wave 5","斗兽场2第5波")
trie.put_if_absent("Colo 2 Wave 6","斗兽场2第6波")
trie.put_if_absent("Colo 2 Wave 7","斗兽场2第7波")
trie.put_if_absent("Colo 2 Wave 8","斗兽场2第8波")
trie.put_if_absent("Colo 2 Wave 9","斗兽场2第9波")
trie.put_if_absent("Colo 2 Wave 10","斗兽场2第10波")
trie.put_if_absent("Colo 2 Wave 11","斗兽场2第11波")
trie.put_if_absent("Colo 2 Wave 12","斗兽场2第12波")
trie.put_if_absent("Colo 2 Wave 13","斗兽场2第13波")
trie.put_if_absent("Colo 2 Wave 14","斗兽场2第14波")
trie.put_if_absent("Colo 2 Wave 15","斗兽场2第15波")
trie.put_if_absent("Colo 2 Wave 16","斗兽场2第16波")
trie.put_if_absent("Colo 2 End","斗兽场2结束")
trie.put_if_absent("Colo 3 Wave 1","斗兽场3第1波")
trie.put_if_absent("Colo 3 Wave 3","斗兽场3第3波")
trie.put_if_absent("Colo 3 Wave 4","斗兽场3第4波")
trie.put_if_absent("Colo 3 Wave 5","斗兽场3第5波")
trie.put_if_absent("Colo 3 Wave 6","斗兽场3第6波")
trie.put_if_absent("Colo 3 Wave 7","斗兽场3第7波")
trie.put_if_absent("Colo 3 Wave 8","斗兽场3第8波")
trie.put_if_absent("Colo 3 Wave 8a","斗兽场3第8a波")
trie.put_if_absent("Colo 3 Wave 8b","斗兽场3第8b波")
trie.put_if_absent("Colo 3 Wave 9a","斗兽场3第9a波")
trie.put_if_absent("Colo 3 Wave 9b","斗兽场3第9b波")
trie.put_if_absent("Colo 3 Wave 10","斗兽场3第10波")
trie.put_if_absent("Colo 3 Wave 11","斗兽场3第11波")
trie.put_if_absent("Colo 3 Wave 12a","斗兽场3第12a波")
trie.put_if_absent("Colo 3 Wave 12b","斗兽场3第12b波")
trie.put_if_absent("Colo 3 Wave 14a","斗兽场3第14a波")
trie.put_if_absent("Colo 3 Wave 14b","斗兽场3第14b波")
trie.put_if_absent("Colo 3 Wave 15","斗兽场3第15波")
trie.put_if_absent("Colo 3 Wave 16","斗兽场3第16波")
trie.put_if_absent("Colo 3 Wave 17a","斗兽场3第17a波")
trie.put_if_absent("Colo 3 Wave 17b","斗兽场3第17b波")
trie.put_if_absent("Colo 3 Wave 17c","斗兽场3第17c波")
trie.put_if_absent("Colo 3 End","斗兽场3结束")
trie.put_if_absent("Rando Wake","随机醒来")
trie.put_if_absent("Completion","完成度")
trie.put_if_absent("Shape of Unn Synergies","乌恩之形的协同作用")
trie.put_if_absent("Pure Snail","纯粹蜗牛")
trie.put_if_absent("All Achievements","全成就")
trie.put_if_absent("Comfy Route","舒适的路线")
trie.put_if_absent("Stag Nest","鹿角虫巢穴")
trie.put_if_absent("QGA","王后花园酸水入口")
trie.put_if_absent("Godseeker mode","寻神者模式")
trie.put_if_absent("Colo 1 w/ Autosplit Waves","愚人斗兽场1")
trie.put_if_absent("Colo 2 w/ Autosplit Waves","愚人斗兽场2")
trie.put_if_absent("Colo 3 w/ Autosplit Waves","愚人斗兽场3")
trie.put_if_absent("Base Game","游戏本体")
trie.put_if_absent("Hidden Dreams","隐藏的梦")
trie.put_if_absent("Lifeblood","生命血")
trie.put_if_absent("Grimm Troupe","格林剧团")
trie.put_if_absent("route","路线")
trie.put_if_absent("All Geo Rocks","全吉欧堆")
trie.put_if_absent("Great Husk Sentry","大型躯壳哨兵")
trie.put_if_absent("Watcher's Spire","守望者的尖塔")
trie.put_if_absent("Fungal Core","真菌核心")
trie.put_if_absent("Stone Sanctuary","石之庇护所")
trie.put_if_absent("Goam","戈姆")
trie.put_if_absent("Hallownest's Crown","圣巢之巅")
trie.put_if_absent("Junk Pit","垃圾坑")
trie.put_if_absent("All Broken Charms","全部破碎的护符")
trie.put_if_absent("Forgotten Corners","遗忘的角落")
trie.put_if_absent("Myla Flower","米拉送花")
trie.put_if_absent("Randomizer TE (add splits as desired)","随机真结局（请自行添加Splits）")
trie.put_if_absent("Shard","碎片")
trie.put_if_absent("MMC","大型苔藓冲锋者")
trie.put_if_absent("Shard/Stag/Sly","碎片/鹿角虫站/斯莱")
trie.put_if_absent("All Bosses","全Boss")
trie.put_if_absent("Notches","护符槽")
trie.put_if_absent("PoP","苦痛之路")
trie.put_if_absent("Rafters","平台")
trie.put_if_absent("Fake Spell Pickup","捡起假法术")
trie.put_if_absent("Main Menu w/ Isma's Tear","回主菜单获得伊思玛的眼泪后")
trie.put_if_absent("Spore Shroom/Deepnest","蘑菇孢子/深巢")
trie.put_if_absent("Reroute","重制路线")
trie.put_if_absent("Failed Champ","失败冠军")
trie.put_if_absent("beat the WR", "打破了世界纪录：")
trie.put_if_absent("in Hollow Knight Category Extensions", "在空洞骑士")
trie.put_if_absent("in Hollow Knight Category Extensions -", "在空洞骑士")
trie.put_if_absent("in Hollow Knight: Silksong Category Extensions", "在丝之歌")
trie.put_if_absent("in Hollow Knight: Silksong Category Extensions -", "在丝之歌")
trie.put_if_absent("King's Pass: Level", "国王山道")
trie.put_if_absent("in Hollow Knight", "在空洞骑士")
trie.put_if_absent("in Hollow Knight -", "在空洞骑士")
trie.put_if_absent("The new WR is", "新的世界纪录是")
trie.put_if_absent("Their time is", "时间是")
trie.put_if_absent("Its time is", "时间是")
trie.put_if_absent("The time is", "时间是")
trie.put_if_absent("His time is", "时间是")
trie.put_if_absent("Her time is", "时间是")
trie.put_if_absent("got a new top 3 PB", "获得了前三：")
trie.put_if_absent("Pantheon of the Master: Level", "大师万神殿")
trie.put_if_absent("Pantheon of the Master Level", "大师万神殿")
trie.put_if_absent("Pantheon of the Artist: Level", "艺术家万神殿")
trie.put_if_absent("Pantheon of the Artist Level", "艺术家万神殿")
trie.put_if_absent("Pantheon of the Sage: Level", "贤者万神殿")
trie.put_if_absent("Pantheon of the Sage Level", "贤者万神殿")
trie.put_if_absent("Pantheon of the Knight: Level", "骑士万神殿")
trie.put_if_absent("Pantheon of the Knight Level", "骑士万神殿")
trie.put_if_absent("Pantheon of Hallownest: Level", "圣巢万神殿")
trie.put_if_absent("Pantheon of Hallownest Level", "圣巢万神殿")
trie.put_if_absent("White Palace: Level", "白色宫殿")
trie.put_if_absent("White Palace Level", "白色宫殿")
trie.put_if_absent("Path of Pain: Level", "苦痛之路")
trie.put_if_absent("Path of Pain Level", "苦痛之路")
trie.put_if_absent("Trial of the Warrior: Level", "勇士的试炼")
trie.put_if_absent("Trial of the Warrior Level", "勇士的试炼")
trie.put_if_absent("Trial of the Conqueror: Level", "征服者的试炼")
trie.put_if_absent("Trial of the Conqueror Level", "征服者的试炼")
trie.put_if_absent("Trial of the Fool: Level", "愚人的试炼")
trie.put_if_absent("Trial of the Fool Level", "愚人的试炼")
trie.put_if_absent("NMG", "无主要邪道")
trie.put_if_absent("NMG.", "无主要邪道.")
trie.put_if_absent("- NMG", "- 无主要邪道")
trie.put_if_absent("- NMG.", "- 无主要邪道.")
trie.put_if_absent("Console Runs", "主机速通")
trie.put_if_absent("Any Bindings", "任意锁")
trie.put_if_absent("Abyss Climb: Level", "深渊攀爬")
trie.put_if_absent("Abyss Climb Level", "深渊攀爬")
trie.put_if_absent("King's Pass: Level", "国王山道")
trie.put_if_absent("King's Pass Level", "国王山道")
trie.put_if_absent("NG", "新存档")
trie.put_if_absent("NG+", "无需新存档")
trie.put_if_absent("NMG NG+", "无主要邪道无需新存档")
trie.put_if_absent("Warpless", "禁SL")
trie.put_if_absent("Hollow Knight: Silksong", "丝之歌")
trie.put_if_absent("Judgement", "末日裁决者")
trie.put_if_absent("Twisted", "畸芽")
trie.put_if_absent("Tools", "工具")
trie.put_if_absent("Awoo", "全跳蚤")
trie.put_if_absent("Individual Level", "")
trie.put_if_absent("Moss Grotto", "苔穴")
trie.put_if_absent("Dapper Slapper", "衣冠楚楚的掌掴者")
trie.put_if_absent("Wishes", "祈愿")
trie.put_if_absent("Slab%", "监狱钟道%")
trie.put_if_absent("Jailed", "被锁住")
trie.put_if_absent("Bellbeast", "钟道兽")
trie.put_if_absent("Furyless", "无亡怒")
trie.put_if_absent("All Bellways", "全钟道")
trie.put_if_absent("Cloakless", "无斗篷")
trie.put_if_absent("No Major Glitches Cloak", "无主要邪道 斗篷线")
trie.put_if_absent("Sinner", "罪途")
trie.put_if_absent("106% TE", "106%")
trie.put_if_absent("107% AB", "107%")
trie.put_if_absent("112% APB", "112%")
trie.put_if_absent("Abyss Climb", "深渊攀爬")